### ISSUE TITLE
`missing trie node:leveldb: not found`and `panic: Refund counter below zero (gas: 15000 > refund: 8400)`

### ISSUE THREAD

**Issue by XWJACK** [MetisProtocol/metis-replica-node#42]
I'm sync from genesis

```
ERROR[03-18|10:49:15.328] missing trie node:leveldb: not found
ERROR[03-18|10:49:15.328] goroutine 687442 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/ethereum-optimism/optimism/l2geth/trie.(*Database).node(0xc0001cc500, {0x5d, 0x9b, 0x56, 0xf1, 0x27, 0xc8, 0x82, 0x3e, 0xee, ...})
	/l2geth/trie/database.go:390 +0x28a
github.com/ethereum-optimism/optimism/l2geth/trie.(*Trie).resolveHash(0xc026197698?, {0xc006c59fe0?, 0x0?, 0x0?}, {0x0, 0x0, 0x0})
	/l2geth/trie/trie.go:392 +0xda
github.com/ethereum-optimism/optimism/l2geth/trie.New({0x5d, 0x9b, 0x56, 0xf1, 0x27, 0xc8, 0x82, 0x3e, 0xee, 0x9, ...}, ...)
	/l2geth/trie/trie.go:71 +0xea
github.com/ethereum-optimism/optimism/l2geth/trie.NewSecure({0x5d, 0x9b, 0x56, 0xf1, 0x27, 0xc8, 0x82, 0x3e, 0xee, 0x9, ...}, ...)
	/l2geth/trie/secure_trie.go:58 +0x2f
github.com/ethereum-optimism/optimism/l2geth/core/state.(*cachingDB).OpenTrie(0xc0056f0000?, {0x5d, 0x9b, 0x56, 0xf1, 0x27, 0xc8, 0x82, 0x3e, 0xee, ...})
	/l2geth/core/state/database.go:124 +0x29
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).HasState(...)
	/l2geth/core/blockchain.go:731
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).HasBlockAndState(0xc0056f0000, {0x5a, 0xd3, 0xfa, 0xe7, 0x8a, 0x93, 0x43, 0x6a, 0xcb, ...}, ...)
	/l2geth/core/blockchain.go:743 +0x7b
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockValidator).ValidateBody(0xc000394a20, 0xc01a7e93b0)
	/l2geth/core/block_validator.go:53 +0x9f
github.com/ethereum-optimism/optimism/l2geth/core.(*insertIterator).next(0xc006c5e3f0)
	/l2geth/core/blockchain_insert.go:121 +0x157
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh(0xc0056f0000, {0xc0022b2000?, 0x800, 0x800}, 0x1, 0xc086202600?, 0xc086202660?, {0xee28a0?, 0xc07154c920})
	/l2geth/core/blockchain.go:2024 +0x101c
created by github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).InsertChainWithFunc in goroutine 1066
	/l2geth/core/blockchain.go:1534 +0xb6d

panic: Refund counter below zero (gas: 15000 > refund: 8400)

goroutine 689115 [running]:
github.com/ethereum-optimism/optimism/l2geth/core/state.(*StateDB).SubRefund(0xc0748f1b00, 0x3a98)
	/l2geth/core/state/statedb.go:224 +0xdc
github.com/ethereum-optimism/optimism/l2geth/core/vm.gasSStoreEIP2200(0xc039300000, 0xc038b35b00, 0xc038b35b00?, 0x12fcb5b?, 0xc03b9bfc20?)
	/l2geth/core/vm/gas_table.go:205 +0x3b0
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc03930a000, 0xc038b35b00, {0xc038b14b84, 0x44, 0x7c}, 0x0)
	/l2geth/core/vm/interpreter.go:261 +0x86e
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc039300000, 0xc038b35b00, {0xc038b14b84, 0x44, 0x7c}, 0x61?)
	/l2geth/core/vm/evm.go:75 +0x3a2
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc039300000, {0x12f98e0, 0xc038b35980}, {0xde, 0xad, 0xde, 0xad, 0xde, 0xad, 0xde, ...}, ...)
	/l2geth/core/vm/evm.go:256 +0x89c
github.com/ethereum-optimism/optimism/l2geth/core/vm.opCall(0xc03b9bfa40?, 0xc03930a000, 0xc038b35980, 0xc0628ba740, 0xc03b9bfa40)
	/l2geth/core/vm/instructions.go:771 +0x30b
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc03930a000, 0xc038b35980, {0xc038bd3cf2, 0xa4, 0x30e}, 0x0)
	/l2geth/core/vm/interpreter.go:277 +0xa96
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc039300000, 0xc038b35980, {0xc038bd3cf2, 0xa4, 0x30e}, 0x16?)
	/l2geth/core/vm/evm.go:75 +0x3a2
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc039300000, {0x12f98e0, 0xc038e32600}, {0x73, 0x2f, 0x7a, 0x4, 0xfa, 0xba, 0x1f, ...}, ...)
	/l2geth/core/vm/evm.go:256 +0x89c
github.com/ethereum-optimism/optimism/l2geth/core/vm.opCall(0xc03ce18f78?, 0xc03930a000, 0xc038e32600, 0xc06ea045c0, 0xc03ce18f78)
	/l2geth/core/vm/instructions.go:771 +0x30b
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc03930a000, 0xc038e32600, {0xc002e11600, 0x1e4, 0x1e4}, 0x0)
	/l2geth/core/vm/interpreter.go:277 +0xa96
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc039300000, 0xc038e32600, {0xc002e11600, 0x1e4, 0x1e4}, 0x5e?)
	/l2geth/core/vm/evm.go:75 +0x3a2
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc039300000, {0x12f9100, 0xc04a986198}, {0x2d, 0x4f, 0x78, 0x8f, 0xdb, 0x26, 0x2a, ...}, ...)
	/l2geth/core/vm/evm.go:256 +0x89c
github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDbWithBlockNumber(0xc02fadf730, 0x0)
	/l2geth/core/state_transition.go:303 +0xb1e
github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDb(...)
	/l2geth/core/state_transition.go:238
github.com/ethereum-optimism/optimism/l2geth/core.ApplyMessage(0x107c1a0?, {0x1307de0?, 0xc0519d1cb0?}, 0x41bd3e4fd8927344?)
	/l2geth/core/state_transition.go:164 +0x25
github.com/ethereum-optimism/optimism/l2geth/core.precacheTransaction(_, {_, _}, _, _, _, _, _, {0x0, {0x0, ...}, ...})
	/l2geth/core/state_prefetcher.go:83 +0x225
github.com/ethereum-optimism/optimism/l2geth/core.(*statePrefetcher).Prefetch(_, _, _, {0x0, {0x0, 0x0}, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
	/l2geth/core/state_prefetcher.go:64 +0x2b4
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh.func2({0x0?, 0x0?, 0x1a598c0?})
	/l2geth/core/blockchain.go:2083 +0x149
created by github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh in goroutine 687442
	/l2geth/core/blockchain.go:2081 +0x1a8a
```

l1dtl.env

```env
URL=https://metisprotocol.github.io/metis-networks/andromeda-mainnet/addresses.json
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://andromeda.metis.io
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=1088
DATA_TRANSPORT_LAYER__DB_PATH=/data/db
DATA_TRANSPORT_LAYER__SERVER_PORT=7878
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
DATA_TRANSPORT_LAYER__CONFIRMATIONS=1
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=60000
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=100
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
DATA_TRANSPORT_LAYER__L1_START_HEIGHT=13625200

DATA_TRANSPORT_LAYER__MINIO_ENABLED=true
DATA_TRANSPORT_LAYER__MINIO_BUCKET=metis-1088-prod
DATA_TRANSPORT_LAYER__MINIO_ENDPOINT=memoapi.metis.io
DATA_TRANSPORT_LAYER__MINIO_PORT=6083
DATA_TRANSPORT_LAYER__MINIO_USE_SSL=true
DATA_TRANSPORT_LAYER__MINIO_ACCESS_KEY=metisread
DATA_TRANSPORT_LAYER__MINIO_SECRET_KEY=8uyywb*7y3

DATA_TRANSPORT_LAYER__BATCH_INBOX_ADDRESS=0xff00000000000000000000000000000000001088
DATA_TRANSPORT_LAYER__BATCH_INBOX_SENDER=0x1a9da0aeda630ddf2748a453bf6d92560762d914
DATA_TRANSPORT_LAYER__DESEQBLOCK=0
DATA_TRANSPORT_LAYER__BATCH_INBOX_START_INDEX=42647
DATA_TRANSPORT_LAYER__BATCH_INBOX_L1_HEIGHT=19438451
```

l2geth.env

```env
VERBOSITY=3
DATADIR=/root/.ethereum
NO_USB=true
IPC_DISABLE=false
MAX_PEER=150
GCMODE=full

USING_OVM=true
CHAIN_ID=1088
NETWORK_ID=1088
TARGET_GAS_LIMIT=1100000000

ETH1_CTC_DEPLOYMENT_HEIGHT=13626959
ETH1_SYNC_SERVICE_ENABLE=false

ROLLUP_BACKEND=l1
ROLLUP_DISABLE_TRANSFERS=false
ROLLUP_ENABLE_L2_GAS_POLLING=false
ROLLUP_MAX_CALLDATA_SIZE=40000
ROLLUP_SYNC_SERVICE_ENABLE=true
ROLLUP_POLL_INTERVAL_FLAG=100ms

# for geth.sh
ROLLUP_STATE_DUMP_PATH=https://metisprotocol.github.io/metis-networks/andromeda-mainnet/state-dump.latest.json
BLOCK_SIGNER_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F
ROLLUP_CLIENT_HTTP=http://dtl:7878

# for rpc/websocket/ipc
RPC_ENABLE=true
RPC_ADDR=0.0.0.0
RPC_PORT=8545
RPC_API=eth,net,web3,mvm,rollupbridge,rpc
RPC_CORS_DOMAIN=*
RPC_VHOSTS=*
RPC_WRITE_TIMEOUT=5s

WS=true
WS_ADDR=0.0.0.0
WS_PORT=8546
WS_API=eth,net,web3,mvm,rollupbridge,rpc
WS_ORIGINS=*

SEQSET_VALID_HEIGHT=15214531
DESEQBLOCK=0
SEQSET_CONTRACT=0x0fe382b74C3894B65c10E5C12ae60Bbd8FAf5b48
SEQ_BRIDGE_URL=https://andromeda.metis.io
BOOTNODES=enode://61b617d2549296b0b950efcf8c1d87227d454d44362e642dde37d83092a445f2b6a6fd651d611b2893249d1e9d15c8f1d4b067142cff53280a08c9c7565c29e2@3.22.33.68:30303,enode://524e335aaa2a4555fe2d54f07fc34da83d80b0407d86c606b76ce918f96a348cf91947f7c60b0eabd29f68d2669cc0ced1360636daa53d0ccc948e154d0ce21e@3.129.121.37:30303,enode://c4cc213e3c5cb57b1ea6e1aa0b8a28240b03a5fa4b65ff08c53faf448182ae161d68c78fe48040da1e5d9087c6f19b60644605c4c2d78845627f09b90207e56c@3.17.198.212:30303

```

docker-compose.yml

```yml
services:
    dtl:
        image: ericlee42/metis:dtl-4
        container_name: metis-dtl
        restart: unless-stopped
        platform: linux/amd64
        stop_grace_period: 30s
        expose:
            - 7878
        volumes:
            - /7t/metis/dtl:/data
        env_file:
            - ./l1dtl.env
            - .env
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:7878"]
            interval: 5s
            timeout: 3s
            retries: 6
        logging:
            driver: "json-file"
            options:
                max-size: "2m"
                max-file: "10"

    geth:
        image: ericlee42/metis:l2geth-5
        container_name: metis-geth
        platform: linux/amd64
        restart: unless-stopped
        stop_grace_period: 2m
        env_file:
            - ./l2geth.env
        depends_on:
            dtl:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:8545"]
            interval: 5s
            timeout: 3s
            retries: 6
        volumes:
            - /7t/metis/geth:/root/.ethereum
        ports:
            - 8530:8545
            - 8531:8546
        logging:
            driver: "json-file"
            options:
                max-size: "2m"
                max-file: "10"

```
